test a merge

diff --git a/.local/bin/setup/install b/.local/bin/setup/install
--- a/.local/bin/setup/install
+++ b/.local/bin/setup/install
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# import lib.sh, has shared code between update and install
+source $HOME/.local/bin/setup/lib.sh
 usage="NAME
       install - install dotfiles project
 
@@ -24,6 +26,8 @@ while test $# -gt 0; do
             exit;;
         -n|--new)
             _new=true;;
+        -q|--quick)
+            _quick=true;;
         -f|--full)
             full=true;;
         -u|--user)
@@ -42,22 +46,22 @@ done
 
 function check_required_params() {
     if [[ -z $github_user ]]; then
-        echo "Github account name required" >&2
+        echo "FATAL: Github account name required" >&2
         exit 1
     fi
 }
 
 function update_pacman() {
-    sudo pacman -Syu --noconfirm
+    sudo pacman -Syu --noconfirm --quiet
     sudo pacman-optimize && sync
 }
 
-function install_pacman_packages() {
-    common_pacman_packages=$(cat ~/.config/dotfiles/arch-packages/pacman)
-    for package_name in $common_pacman_packages; do
-        sudo pacman -S $package_name --needed --noconfirm --quiet
-    done
-}
+# function install_pacman_packages() {
+#     common_pacman_packages=$(cat ~/.config/dotfiles/arch-packages/pacman)
+#     for package_name in $common_pacman_packages; do
+#         sudo pacman -S $package_name --needed --noconfirm --quiet
+#     done
+# }
 
 #pacman-contrib:
 #  used for 'checkupdates' command in polybar module that shows how many updates pacman has
@@ -66,8 +70,14 @@ function install_pacman_packages() {
 # list of packages no longer used
 # to be removed from system to avoid issues
 remove_packages="
+"
+
+remove_aur_packages="
     ttf-font-awesome
     i3blocks-gaps-git
+    hipchat
+    slack-desktop
+    rtv
 "
 
 # virtualbox-guest-modules-arch
@@ -92,19 +102,20 @@ function install_virtual_machine_needed_packages() {
 function uninstall_deprecated_packages() {
     echo 'removing packages that are no longer needed'
     for package_name in $remove_packages; do
-        sudo pacman -R --noconfirm
+        sudo pacman -R --noconfirm $package_name
+    done
+    for package_name in $remove_aur_packages; do
+        trizen -R --noconfirm $package_name
     done
 }
 
-trizen -Sa --needed yay --noconfirm --noedit
-
-trizen -Sa --needed yay --noconfirm --noedit
+slow_aur_packages="
+    polybar-git
+    paper-icon-theme-git
+"
 
 core_aur_packages="
     i3-gaps-next-git
-    polybar-git
-    paper-icon-theme-git
-    awesome-terminal-fonts
     exa
     ccat
     xorg-xprop
@@ -114,8 +125,10 @@ core_aur_packages="
     mirage
     arc-gtk-theme
     awesome-terminal-fonts
+    flashfocus-git
 "
 function install_aur_packages() {
+    trizen -Sa --needed yay --noconfirm --noedit
     ## RUST
     # some aur packages require compiling rust code
     # so this intializes rust
@@ -125,22 +138,31 @@ function install_aur_packages() {
     for aur_package in $core_aur_packages; do
     yay -Sy --aur $aur_package --answerupgrade none --answerdiff none --answeredit none --answerclean none
     done
+
+    if [[ $_quick != true ]]; then
+        # if polybar is installed before i3 it doesn't install compatibility with i3
+        for pkg in $slow_aur_packages; do
+            yay -Sy --aur $aur_package --answerupgrade none --answerdiff none --answeredit none --answerclean none
+        done
+    fi
 }
 
+## Packages that take forever to install:
+# - paper-icon-theme-git 
+# - polybar (needs to compile c++)
 function install_extra_aur_packages() {
     if [[ $full = true ]]; then
         ## install aur packages
         aur_packages="
-            hipchat
+            terraform
+            ansible
             spotify
             dropbox
-            rtv
             siji-git
             xorg-xset
             remmina-plugin-rdesktop
             pgadmin4
             cli-visualizer
-            slack-desktop
             teams-for-linux
             antibody-bin
     "
@@ -169,7 +191,8 @@ function install_docker() {
     fi
 }
 
-function install_oh-my-zsh_and_plugins() {
+function install_oh_my_zsh_and_plugins() {
+    pacman -S zsh --no-confirm
     ## Install oh-my-zsh
     sh /home/$USER/.local/bin/tools/install_oh_my_zsh
     yadm reset --hard origin/master
@@ -237,11 +260,23 @@ fi
 #     done
 # }
 
-
 # TODO: add golang setup back in
-# needed for spacemacs go layer
-# https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go
+function install_golang_packages() {
 
+    # needed for spacemacs go layer
+    # https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go
+    go get -u -v github.com/nsf/gocode
+    go get -u -v github.com/rogpeppe/godef
+    go get -u -v golang.org/x/tools/cmd/guru
+    go get -u -v golang.org/x/tools/cmd/gorename
+    go get -u -v golang.org/x/tools/cmd/goimports
+
+    # needed for guru -> import/add dependencies (spacemacs go layer)
+    go get -u -v github.com/uudashr/gopkgs/cmd/gopkgs
+
+    # needed for dotfiles
+    go get -u -v github.com/patrick-motard/dot
+}
 # gopath isn't set, so this trys to make a dir in /src which
 # gives permission denied. subsequent calls to the script succeed beacuse .zshrc is sourced and gopath is set there.
 # mkdir -p $GOPATH/src/github.com
@@ -254,17 +289,67 @@ fi
 xdg-settings set default-web-browser google-chrome.desktop
 
 function main() {
+    source $HOME/.profile
+    echo "1. ### Checking required params ###"
+    echo ""
+    echo ""
     check_required_params
-    update_pacman
-    install_pacman_packages
-    install_aur_packages
-    install_extra_aur_packages
-    install_docker
-    install_node_packages
-    install_python_packages
 
-    if [[ _new == true ]]; then
-        install_oh-my-zsh_and_plugins
+    echo "2. ### Updating Pacman ###"
+    echo ""
+    echo ""
+    update_pacman
+
+    if [[ $_new == true ]]; then
+        install_oh_my_zsh_and_plugins
+        echo "11. ### Installing oh-my-zsh and it's plugins ###"
+        echo ""
+        echo ""
+    fi
+
+    echo "3. ### Updating Pacman Packages ###"
+    echo ""
+    echo ""
+    install_pacman_packages
+    echo "4. ### Installing AUR packages ###"
+    echo ""
+    echo ""
+    install_aur_packages
+    echo "5. ### AUR ###"
+    echo ""
+    echo ""
+
+    # install_extra_aur_packages
+    echo "6. ### DOCKER ###"
+    echo ""
+    echo ""
+
+    # install_docker
+
+    echo "8. ### PYTHON ###"
+    echo ""
+    echo ""
+
+    install_python_packages
+    echo "9. ### GOLANG ###"
+    echo ""
+    echo ""
+
+    install_golang_packages
+    echo "10. ### Uninstalling Deprecated Packages ###"
+    echo ""
+    echo ""
+
+    # uninstall_deprecated_packages
+
+    echo "7. ### NODE ###"
+    echo ""
+    echo ""
+
+    # node has to happen after zsh because nvm is installed as a zsh plugin
+    # install_node_packages
+    if [[ $_new == true ]]; then
+        # echo hello
         reboot
     fi
 }
