merge in some of patrick's changes

diff --git a/.local/bin/setup/install b/.local/bin/setup/install
--- a/.local/bin/setup/install
+++ b/.local/bin/setup/install
@@ -7,29 +7,27 @@ SYNOPSIS
 
 ARGUMENTS
 
-       -r|--restart
-          Restart after completion
-       -c|--core
-          Only install core packages from arch and aur.
+
+       -f|--full)
+          Do a full install. Including all AUR packages, not just required ones.
        -u|--user
           Name of your github account where dotfiles was forked to.
+       -n|--new
+          Indicate this is being run on a new install. This script needs to reset certain
+          files during the initial setup. This flag allows it to do so.
 "
 
 while test $# -gt 0; do
 	  case "$1" in
         -h|--help|-\?)
             echo "$usage" >&2
-            exit
-            ;;
-        -r|--restart)
-            _restart=true
-            shift ;;
-        -c|--core)
-            core=true
-            ;;
+            exit;;
+        -n|--new)
+            _new=true;;
+        -f|--full)
+            full=true;;
         -u|--user)
             github_user=$2
-            echo $2
             shift
             ;;
         \?)
@@ -42,81 +40,27 @@ while test $# -gt 0; do
     shift
 done
 
-if [[ -z $github_user ]]; then
-    echo "Github account name required" >&2
-    exit 1
-fi
+function check_required_params() {
+    if [[ -z $github_user ]]; then
+        echo "Github account name required" >&2
+        exit 1
+    fi
+}
 
-sudo pacman -Syu --noconfirm
-sudo pacman-optimize && sync
+function update_pacman() {
+    sudo pacman -Syu --noconfirm
+    sudo pacman-optimize && sync
+}
 
-common_pacman_packages="
-    xorg-server
-    jq
-    xorg-xinit
-    gvim
-    zsh
-    keychain
-    xclip
-    python-pip
-    firefox
-    termite
-    rofi
-    emacs
-    compton
-    pulseaudio
-    pavucontrol
-    pamixer
-    alsa-utils
-    feh
-    docker
-    docker-compose
-    thunar
-    htop
-    tumbler
-    weechat
-    xbindkeys
-    tree
-    facter
-    xf86-video-vesa
-    nvidia
-    scrot
-    i3lock
-    ranger
-    fcron
-    dunst
-    qutebrowser
-    xorg-xfd
-    screenfetch
-    remmina
-    libreoffice-fresh
-    task
-    gtop
-    perl-anyevent-i3
-    rustup
-    nmap
-    freerdp
-    go-tools
-    ntp
-    networkmanager-dispatcher-ntpd
-    bitlbee
-    ncurses
-    fftw
-    groovy
-    pacman-contrib
-    cloc
-    xorg-xrandr
-    xautolock
-"
+function install_pacman_packages() {
+    common_pacman_packages=$(cat ~/.config/dotfiles/arch-packages/pacman)
+    for package_name in $common_pacman_packages; do
+        sudo pacman -S $package_name --needed --noconfirm --quiet
+    done
+}
+
 #pacman-contrib:
 #  used for 'checkupdates' command in polybar module that shows how many updates pacman has
-
-# https://github.com/dpayne/cli-visualizer
-# pacman:
-#    ncurses
-#    fftw
-# aur:
-#    cli-visualizer
 
 
 # list of packages no longer used
@@ -134,31 +78,23 @@ virtualbox_packages="
 physical_packages="
 "
 
-# install common packages
-for package_name in $common_pacman_packages; do
-  sudo pacman -S $package_name --needed --noconfirm --quiet
-done
+function install_virtual_machine_needed_packages() {
+    # install/update packages for virtualbox or physical install
+    [[ "$(facter is_virtual)" == true ]] && \
+        host_specific_pkgs=$virtualbox_packages || \
+            host_specific_pkgs=$physical_packages
+    echo 'installing host specific packages'
+    for package_name in $host_specific_pkgs; do
+        sudo pacman -S $package_name --needed --noconfirm
+    done
+}
 
-# install/update packages for virtualbox or physical install
-[[ "$(facter is_virtual)" == true ]] && \
-    host_specific_pkgs=$virtualbox_packages || \
-        host_specific_pkgs=$physical_packages
-
-echo 'installing host specific packages'
-for package_name in $host_specific_pkgs; do
-    sudo pacman -S $package_name --needed --noconfirm
-done
-
-echo 'removing packages that are no longer needed'
-for package_name in $remove_packages; do
-    sudo pacman -R --noconfirm
-done
-
-## RUST
-rustup install stable
-rustup default stable
-## END RUST
-
+function uninstall_deprecated_packages() {
+    echo 'removing packages that are no longer needed'
+    for package_name in $remove_packages; do
+        sudo pacman -R --noconfirm
+    done
+}
 core_aur_packages="
     i3-gaps-next-git
     polybar-git
@@ -174,78 +110,99 @@ core_aur_packages="
     arc-gtk-theme
     awesome-terminal-fonts
 "
-for aur_package in $core_aur_packages; do
-    trizen -Sa --needed $aur_package --noconfirm --noedit
-done
-if [[ $core != true ]]; then
-    ## install aur packages
-    aur_packages="
-        spotify
-        dropbox
-        rtv
-        siji-git
-        xorg-xset
-        remmina-plugin-rdesktop
-        pgadmin4
-        cli-visualizer
-        slack-desktop
-        teams-for-linux
-        glxinfo
-        vault
-        google-chrome
-        google-chrome-beta
-        xprintidle
-"
-    for aur_package in $aur_packages; do
-        trizen -Sa --needed $aur_package --noconfirm --noedit
+function install_aur_packages() {
+    ## RUST
+    # some aur packages require compiling rust code
+    # so this intializes rust
+    rustup install stable
+    rustup default stable
+    ## END RUST
+    for aur_package in $core_aur_packages; do
+        trizen -S --needed $aur_package --noconfirm --noedit
     done
-fi
+}
 
-## if the docker daemon isn't active, set it up
-systemctl -q is-active docker
-if [[ $? -ne 0 ]] ; then
-    echo "Docker isn't running"
-    ## refer to docker daemon documentation for further details:
-    ## https://docs.docker.com/engine/installation/linux/linux-postinstall/
-    ## create a group for docker
-    sudo groupadd docker
-    ## add current user to it so that you dont have to issue sudo everytime
-    sudo usermod -aG docker $USER
-    ## make sure the docker daemon starts on boot
-    sudo systemctl enable docker
-    ## start the docker daemon
-    sudo systemctl start docker
-    echo "Docker now running and set to run on boot. User added to group"
-fi
+function install_extra_aur_packages() {
+    if [[ $full = true ]]; then
+        ## install aur packages
+        aur_packages="
+            hipchat
+            spotify
+            dropbox
+            rtv
+            siji-git
+            xorg-xset
+            remmina-plugin-rdesktop
+            pgadmin4
+            cli-visualizer
+            slack-desktop
+            teams-for-linux
+    "
+        for aur_package in $aur_packages; do
+            trizen -S --needed $aur_package --noconfirm --noedit
+        done
+    fi
+}
+
+function install_docker() {
+    ## if the docker daemon isn't active, set it up
+    systemctl -q is-active docker
+    if [[ $? -ne 0 ]] ; then
+        echo "Docker isn't running"
+        ## refer to docker daemon documentation for further details:
+        ## https://docs.docker.com/engine/installation/linux/linux-postinstall/
+        ## create a group for docker
+        sudo groupadd docker
+        ## add current user to it so that you dont have to issue sudo everytime
+        sudo usermod -aG docker $USER
+        ## make sure the docker daemon starts on boot
+        sudo systemctl enable docker
+        ## start the docker daemon
+        sudo systemctl start docker
+        echo "Docker now running and set to run on boot. User added to group"
+    fi
+}
+
+function install_oh-my-zsh_and_plugins() {
+    ## Install oh-my-zsh
+    sh /home/$USER/.local/bin/tools/install_oh_my_zsh
+    yadm reset --hard origin/master
+    # uses: https://github.com/lukechilds/zsh-nvm
+    git clone https://github.com/lukechilds/zsh-nvm \
+        ${ZSH_CUSTOM:-/home/$USER/.oh-my-zsh/custom}/plugins/zsh-nvm 2>/dev/null
+    # nvm will globally install all packages listed in ~/.nvm/default-packages
+    # TODO: this symlink needs to be made AFTER nvm is installed, which doesn't
+    # happen until after .zshrc is sourced. Need to figure this out before enabling
+    # this line
+    # ln -s ~/.config/nvm/default-packges ~/.nvm/default-packages
+
+    git clone https://github.com/zsh-users/zsh-autosuggestions \
+        ${ZSH_CUSTOM:-/home/$USER/.oh-my-zsh/custom}/plugins/zsh-autosuggestions 2>/dev/null
+}
+
+function install_node_packages() {
+    # note: this function must be run after install_oh-my-zsh_and_plugins
+    . /home/$USER/.nvm/nvm.sh ## source nvm
+    node_version=$(<~/.nvmrc)
+    nvm install $node_version
+    npm i -g tern ## tern is used for the javascript layer in emacs
+}
 
 
-## Install oh-my-zsh
-sh ~/.local/bin/tools/install_oh_my_zsh
-git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
+function install_python_packages() {
+    ## Python package installs
+    pip install --upgrade --user pip
+    pip install --upgrade --user wakatime
+    pip install --upgrade --user awscli
+    pip install --upgrade --user polybar-reload
+}
 
-## Python package installs
-## Install wakatime
-pip install --upgrade --user pip
-sudo pip install wakatime
-pip install --upgrade --user awscli
-pip install --upgrade --user polybar-reload
 
 ## Install Vundle
 ## commented out check for directory because it already exists. need to solve this problem another way.
 #if [[ ! -d /home/han/.vim/bundle/Vundle.vim ]]; then
-git clone https://github.com/VundleVim/Vundle.vim.git /home/$USER/.vim/bundle/Vundle.vim
+git clone https://github.com/VundleVim/Vundle.vim.git /home/$USER/.vim/bundle/Vundle.vim 2>/dev/null
 #fi
-
-## Install NVM if nvm shell sript not downloaded
-if [[ ! -f .nvm/nvm.sh ]]; then
-  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
-  . ~/.nvm/nvm.sh ## source nvm
-  nvm install --lts=boron
-  npm i -g tern ## tern is used for the javascript layer in emacs
-  npm i vmd ## used for markdown in emacs
-else
-    echo "NVM already installed, skipping..."
-fi
 
 mkdir -p $HOME/code
 
@@ -274,6 +231,7 @@ fi
 # }
 
 
+# TODO: add golang setup back in
 # needed for spacemacs go layer
 # https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go
 
@@ -288,9 +246,20 @@ fi
 
 xdg-settings set default-web-browser google-chrome.desktop
 
-yadm reset --hard origin/master
+function main() {
+    check_required_params
+    update_pacman
+    install_pacman_packages
+    install_aur_packages
+    install_extra_aur_packages
+    install_docker
+    install_node_packages
+    install_python_packages
 
-if [[ _restart == true ]]; then
-    yadm reset --hard origin/master
-    reboot
-fi
+    if [[ _new == true ]]; then
+        install_oh-my-zsh_and_plugins
+        reboot
+    fi
+}
+
+main
